"""Add Short Direction Analysis cell to NB06 and implement asymmetric confidence."""
import json

nb_path = "notebooks/06_backtest.ipynb"
with open(nb_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# ── Cell: Short vs Long Direction Forensics ──
short_analysis_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ============================================================\n",
        "#  SHORT vs LONG DIRECTION FORENSICS\n",
        "#  Runs both directions with NO execution filters to see raw\n",
        "#  model signal quality per direction, per year, per confidence.\n",
        "# ============================================================\n",
        "import warnings\n",
        "warnings.filterwarnings('ignore')\n",
        "\n",
        "seq_len_d = config.model.seq_len\n",
        "HOLD_BARS_D = 10\n",
        "CONF_MIN_D = 0.40\n",
        "RT_COST_D = 0.0008  # 8 bps\n",
        "\n",
        "close_d = df['close'].values\n",
        "diag_all = []\n",
        "\n",
        "for fold_data in wf_predictions:\n",
        "    test_start = fold_data['test_start']\n",
        "    preds = fold_data['test_probabilities']\n",
        "    pred_offset = test_start + seq_len_d\n",
        "\n",
        "    for i in range(len(preds)):\n",
        "        bar = pred_offset + i\n",
        "        exit_bar = bar + HOLD_BARS_D\n",
        "        if exit_bar >= len(df):\n",
        "            break\n",
        "\n",
        "        p_arr = preds[i]\n",
        "        cls = int(np.argmax(p_arr))\n",
        "        if cls == 1:  # Hold\n",
        "            continue\n",
        "\n",
        "        conf = max(p_arr[0], p_arr[2])\n",
        "        if conf < CONF_MIN_D:\n",
        "            continue\n",
        "\n",
        "        entry_price = close_d[bar]\n",
        "        exit_price = close_d[exit_bar]\n",
        "        raw_ret = (exit_price - entry_price) / entry_price\n",
        "        if cls == 0:  # Short\n",
        "            raw_ret = -raw_ret\n",
        "\n",
        "        direction = 'SHORT' if cls == 0 else 'LONG'\n",
        "        diag_all.append({\n",
        "            'bar': bar,\n",
        "            'direction': direction,\n",
        "            'confidence': conf,\n",
        "            'raw_return': raw_ret,\n",
        "            'net_return': raw_ret - RT_COST_D,\n",
        "            'timestamp': df.index[bar],\n",
        "            'year': df.index[bar].year,\n",
        "            'adx': df.iloc[bar].get('adx', 0),\n",
        "            'funding_z': df.iloc[bar].get('funding_rate_zscore', 0),\n",
        "        })\n",
        "\n",
        "diag_all_df = pd.DataFrame(diag_all)\n",
        "\n",
        "print('=' * 80)\n",
        "print('  SHORT vs LONG PURE SIGNAL FORENSICS (No SL/TP, Hold 10 bars, Conf>=0.40)')\n",
        "print('=' * 80)\n",
        "\n",
        "for direction in ['LONG', 'SHORT']:\n",
        "    sub = diag_all_df[diag_all_df['direction'] == direction]\n",
        "    n = len(sub)\n",
        "    if n == 0:\n",
        "        print(f'\\n--- {direction}: No trades ---')\n",
        "        continue\n",
        "    wr = (sub['raw_return'] > 0).mean()\n",
        "    gross_mean = sub['raw_return'].mean()\n",
        "    net_mean = sub['net_return'].mean()\n",
        "    wins = sub.loc[sub['raw_return'] > 0, 'raw_return']\n",
        "    losses = sub.loc[sub['raw_return'] < 0, 'raw_return']\n",
        "    pf = abs(wins.sum() / losses.sum()) if len(losses) > 0 else float('inf')\n",
        "    print(f'\\n--- {direction} ---')\n",
        "    print(f'  Trades: {n:,}')\n",
        "    print(f'  Win Rate: {wr*100:.1f}%')\n",
        "    print(f'  Profit Factor: {pf:.4f}')\n",
        "    print(f'  Gross Mean Return: {gross_mean*100:.4f}%')\n",
        "    print(f'  Net Mean Return:   {net_mean*100:.4f}% (after 8bps)')\n",
        "    print(f'  Cumulative GROSS:  {sub[\"raw_return\"].sum()*100:.2f}%')\n",
        "    print(f'  Cumulative NET:    {sub[\"net_return\"].sum()*100:.2f}%')\n",
        "\n",
        "# Per-direction per-year breakdown\n",
        "print('\\n' + '=' * 80)\n",
        "print('  PER-DIRECTION YEARLY BREAKDOWN')\n",
        "print('=' * 80)\n",
        "pivot = diag_all_df.pivot_table(\n",
        "    index='year', columns='direction',\n",
        "    values='net_return',\n",
        "    aggfunc=['count', 'mean', 'sum']\n",
        ")\n",
        "pivot.columns = [f'{agg}_{dir}' for agg, dir in pivot.columns]\n",
        "# Convert to percentages\n",
        "for c in pivot.columns:\n",
        "    if 'mean' in c or 'sum' in c:\n",
        "        pivot[c] = pivot[c] * 100\n",
        "print(pivot.to_string())\n",
        "\n",
        "# Short performance by confidence bucket\n",
        "print('\\n' + '=' * 80)\n",
        "print('  SHORT PERFORMANCE BY CONFIDENCE BUCKET')\n",
        "print('=' * 80)\n",
        "short_df = diag_all_df[diag_all_df['direction'] == 'SHORT'].copy()\n",
        "if len(short_df) > 0:\n",
        "    short_df['conf_bucket'] = pd.cut(short_df['confidence'], bins=[0.4, 0.5, 0.55, 0.6, 0.7, 0.8, 1.0])\n",
        "    sb = short_df.groupby('conf_bucket', observed=True).agg(\n",
        "        n=('net_return', 'count'),\n",
        "        mean_net_ret=('net_return', 'mean'),\n",
        "        win_rate=('raw_return', lambda x: (x > 0).mean()),\n",
        "        cum_net=('net_return', 'sum'),\n",
        "    )\n",
        "    sb['mean_net_ret'] = sb['mean_net_ret'] * 100\n",
        "    sb['win_rate'] = sb['win_rate'] * 100\n",
        "    sb['cum_net'] = sb['cum_net'] * 100\n",
        "    print(sb.to_string())\n",
        "\n",
        "# Short performance by ADX bucket\n",
        "print('\\n' + '=' * 80)\n",
        "print('  SHORT PERFORMANCE BY ADX LEVEL')\n",
        "print('=' * 80)\n",
        "if len(short_df) > 0:\n",
        "    short_df['adx_bucket'] = pd.cut(short_df['adx'], bins=[0, 15, 20, 25, 30, 40, 100])\n",
        "    sa = short_df.groupby('adx_bucket', observed=True).agg(\n",
        "        n=('net_return', 'count'),\n",
        "        mean_net_ret=('net_return', 'mean'),\n",
        "        win_rate=('raw_return', lambda x: (x > 0).mean()),\n",
        "        cum_net=('net_return', 'sum'),\n",
        "    )\n",
        "    sa['mean_net_ret'] = sa['mean_net_ret'] * 100\n",
        "    sa['win_rate'] = sa['win_rate'] * 100\n",
        "    sa['cum_net'] = sa['cum_net'] * 100\n",
        "    print(sa.to_string())\n",
        "\n",
        "# Short performance by funding rate zscore\n",
        "print('\\n' + '=' * 80)\n",
        "print('  SHORT PERFORMANCE BY FUNDING RATE ZSCORE')\n",
        "print('=' * 80)\n",
        "if len(short_df) > 0:\n",
        "    short_df['funding_bucket'] = pd.cut(short_df['funding_z'], bins=[-10, -1, 0, 0.5, 1, 2, 10])\n",
        "    sf = short_df.groupby('funding_bucket', observed=True).agg(\n",
        "        n=('net_return', 'count'),\n",
        "        mean_net_ret=('net_return', 'mean'),\n",
        "        win_rate=('raw_return', lambda x: (x > 0).mean()),\n",
        "        cum_net=('net_return', 'sum'),\n",
        "    )\n",
        "    sf['mean_net_ret'] = sf['mean_net_ret'] * 100\n",
        "    sf['win_rate'] = sf['win_rate'] * 100\n",
        "    sf['cum_net'] = sf['cum_net'] * 100\n",
        "    print(sf.to_string())\n",
        "\n",
        "print('\\n' + '=' * 80)\n",
        "print('  SUMMARY')\n",
        "print('=' * 80)\n",
        "long_net = diag_all_df.loc[diag_all_df['direction']=='LONG', 'net_return'].sum()\n",
        "short_net = diag_all_df.loc[diag_all_df['direction']=='SHORT', 'net_return'].sum()\n",
        "print(f'  LONG  cumulative net: {long_net*100:+.2f}%')\n",
        "print(f'  SHORT cumulative net: {short_net*100:+.2f}%')\n",
        "print(f'  COMBINED net:         {(long_net+short_net)*100:+.2f}%')\n",
        "if short_net < 0:\n",
        "    print(f'\\n  ⚠️  SHORT trades are NET NEGATIVE. Short is destroying {abs(short_net)*100:.1f}% of Long gains.')\n",
        "    print(f'  → Consider: higher short_conf_threshold, regime filter, or long_only mode.')\n",
        "else:\n",
        "    print(f'\\n  ✅ SHORT trades are NET POSITIVE! Adding {short_net*100:.1f}% to overall PnL.')\n"
    ]
}

# Insert after the last results cell (before the closing of cells array)
# Find the last code cell position and insert after it
nb["cells"].append(short_analysis_cell)

with open(nb_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Done: added Short vs Long Direction Forensics cell to NB06.")
